### ISSUE TITLE
 'Not enough valid windows to create a fit.'

### ISSUE THREAD

**Issue by JasperMore** [peter-moran/highway-lane-tracker#1]
Hello, I'm a student and interested your project.
When I use the "find_lane.py", I got mistakes.
The Error is "assert len(win_left_valid) >= 3 and len(win_right_valid) >= 3, 'Not enough valid windows to create a fit.'"
I check the code, and find that when the function "filter_window_list" ( which is in windows.py) work, all variable of window.dropped, window.frozen, window.detected are True, and it makes all windows can not be appended in variable "windows_filtered". 
Although, there is tips " # TODO: Do something if not enough windows to fit. Most likely fall back on old measurements." in "find_lane.py", I do not know how to fix it. Can you help me? Thank you !

**Comment by JasperMore** [comment]
I use the code in both python 2 and python 3，I found the error only happen in python 2. How can I fix it in python 2 ？

**Comment by peter-moran** [comment]
I'm not sure why you get the specific errors in Python 2, but it's most likely because I'm using Python 3 versions for each of my libraries.

In any case, as long as you use Python 3 you should be about to check out the project.

**Comment by JasperMore** [comment]
Thank you so much for your reply ! I will run the code in python3, and it is successful.

When I read the code, I found the package 'symfit' (it is used in function "fit_lanes(self, points_left, points_right, fit_globally=False) ") cost much time to fit line. I use 'np.polyfit' to replace  'symfit' to fit line and cost less time. In the code, quadratic function is enough to fit the line, so I think 'np.polyfit' might more appropriate to fit line.

**Comment by peter-moran** [comment]
Thanks for pointing that out. The only reason I'm using symfit in the first place was to experiment with different fitting methods (such as enforcing the line to be parallel), but ultimately fitting them with a plain polynomial did best.

**Comment by pengyiwu** [comment]
I got the same error as JasperMore.I ran the code in python 3.6,for the first time,it succeeded. When i changed a input video and ran the code again, i got the same error:Not enough valid windows to create a fit.I am confused.
Thanks so much.
Have a nice day!

**Comment by peter-moran** [comment]
The system is trying to determine what tracking points (windows) along the lane line are useful to use. When that particular assert fails, it means that there are not enough tracking points that the system was confident about to use.

If you take a look at the example videos. You can see the tracking windows pop in and out. This is because there is sometimes parts of the line missing (such as in a dashed line) or the first step failed at identifying the potential line segments.

The assert failing on another video means that the system would need to be reconsidered for more generalizable behavior. In particular, it could do much better at creating the initial binary image of potential lane line areas, which could maybe be aided by a neural network instead of the hand tuned parameters used here.

If you just want to get it to work, you will need to re tune the system to hold onto windows longer or to select more windows. Oututting the video of intermediate steps could help you see what parts are taking the system.

**Comment by tnlxlnt** [comment]
> I got the same error as JasperMore.I ran the code in python 3.6,for the first time,it succeeded. When i changed a input video and ran the code again, i got the same error:Not enough valid windows to create a fit.I am confused. Thanks so much. Have a nice day!

你好，可以帮忙调一下这个代码吗，我弄了几天了，毫无进展

**Comment by tnlxlnt** [comment]
> Hello, I'm a student and interested your project. When I use the "find_lane.py", I got mistakes. The Error is "assert len(win_left_valid) >= 3 and len(win_right_valid) >= 3, 'Not enough valid windows to create a fit.'" I check the code, and find that when the function "filter_window_list" ( which is in windows.py) work, all variable of window.dropped, window.frozen, window.detected are True, and it makes all windows can not be appended in variable "windows_filtered". Although, there is tips " # TODO: Do something if not enough windows to fit. Most likely fall back on old measurements." in "find_lane.py", I do not know how to fix it. Can you help me? Thank you !

你好，可以帮忙运行一下这个吗
